<a href="https://colab.research.google.com/github/hub-mayank/Data-Science/blob/main/Lecture_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question-1 (numpy)

In [ ]:
import numpy as np
a = np.random.randint(1,91,(5,5))
# b = a.reshape(5,5)
print(a)

m = np.mean(a,axis = 1)
print("\n Mean(row): ",m)
mn = np.mean(a,axis = 0)
print("\n Mean(column): ",mn)

s = np.sum(a,axis=1)
print("\n Sum(row) : ",s)
sm = np.sum(a,axis=0)
print("\n Sum(column) : ",sm)

a = np.sort(a,axis=1)
a = np.sort(a,axis=0)
print("\nSorted :\n",a)

mod = np.where(a%2==0,-1,a)
print("\nModified :\n",mod)


cnt = np.sum(np.where(mod<0,1,0))

print("\nNo. of negatives:",cnt)




[[26 64 39 48 45]
 [39 75 74 48 50]
 [81  7 86 75 14]
 [11 58 49 21 56]
 [70 16 21 88 56]]

 Mean(row):  [44.4 57.2 52.6 39.  50.2]

 Mean(column):  [45.4 44.  53.8 56.  44.2]

 Sum(row) :  [222 286 263 195 251]

 Sum(column) :  [227 220 269 280 221]

Sorted :
 [[ 7 14 45 48 58]
 [11 21 49 56 64]
 [16 21 50 70 75]
 [26 39 56 74 86]
 [39 48 75 81 88]]

Modified :
 [[ 7 -1 45 -1 -1]
 [11 21 49 -1 -1]
 [-1 21 -1 -1 75]
 [-1 39 -1 -1 -1]
 [39 -1 75 81 -1]]

No. of negatives: 14


# Question-2

In [ ]:
stock = np.random.randint(20,101,(5,5))
print("\nStock:\n",stock)
demand = np.random.randint(10,60,(5,5))
print("\nDemand:\n",demand)

stock = stock - demand
print("\nAfter Market :\n",stock)

stock = np.where(stock<0,0,stock)
print("\nCurrent stocks :\n",stock)


cnt = np.sum(np.where(stock<=0,1,0))
print("\nProducts with shortage", cnt)
print("\nProducts with no shortage :",25-cnt)

stock = np.sort(stock,axis=0)
print("\nSorted:\n",stock)








Stock:
 [[ 89  33  56  67 100]
 [ 26  59  31  41  79]
 [ 58  86  54  31  69]
 [ 65  79  68  71  88]
 [ 30  22  90  54  98]]

Demand:
 [[57 24 20 55 49]
 [12 41 25 54 29]
 [31 31 13 49 11]
 [54 31 32 32 57]
 [57 29 53 47 33]]

After Market :
 [[ 32   9  36  12  51]
 [ 14  18   6 -13  50]
 [ 27  55  41 -18  58]
 [ 11  48  36  39  31]
 [-27  -7  37   7  65]]

Current stocks :
 [[32  9 36 12 51]
 [14 18  6  0 50]
 [27 55 41  0 58]
 [11 48 36 39 31]
 [ 0  0 37  7 65]]

Products with shortage 4

Products with no shortage : 21

Sorted:
 [[ 0  0  6  0 31]
 [11  9 36  0 50]
 [14 18 36  7 51]
 [27 48 37 12 58]
 [32 55 41 39 65]]


# **Pandas** - Library

In [88]:
import pandas as pd
file_ = pd.read_csv('student_data.csv', sep=',') # separator is used to specify data separation, by default comma
print(file_) #prints the whole data

print("\n")

print(file_.head(4)) #gives no. of rows from start

print(file_.tail(4)) #gives no. of rows from end





   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17           Placed  
      study_hours  attendance  sleep_hours  internet_usage  \
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  pr