<a href="https://colab.research.google.com/github/hub-mayank/Data-Science/blob/main/Lecture_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# #Numpy

In [ ]:
import numpy as np
z = np.array([1,2,3,4,0,9,6,8,1,'2', 4, False]) #creates an array with single datatype
print(a)

# numpy arrays are also called as vectors!

np_array = np.array([3,3,4,5,4.5,"Hello", False])
print(bool(np_array[-1]))

['1' '2' '3' '4' '0' '9' '6' '8' '1' '2' '4' 'False']
True


# Functions

**Array creation**

In [ ]:
a = np.zeros([4,5,2], dtype=int)
print(type(z[0][0][0]))

<class 'numpy.int64'>


In [ ]:
a = np.ones([4,5,2,3], dtype=int)
print(type(a[0][0][0][0]))

<class 'numpy.int64'>


In [ ]:
a = np.empty(4, dtype=int)
print((a))

[967684388         0         0         0]


In [ ]:
a = np.full(4,5, dtype=int)
print((a))

[5 5 5 5]


In [ ]:
z = np.array([1,5,8,32,5])
b = np.arange(3,22,2)  # start, end, steps ----> creates the range
print(b)

c = np.linspace(1,19,4, dtype=int) # (start, end, number of values (evenly distributed)) ----> real data science thing
print(c)

[ 3  5  7  9 11 13 15 17 19 21]
[ 1  7 13 19]


**Array Inspection**

In [ ]:
a = np.array([[2,3,5,8,12,3],[4,5,6,3,4,6]])
print((np.shape(a)))
print(np.size(a))

print('\n')

x = np.random.randint(5,10,3) #(start, stop, size) ----> gives random values between the range (can have duplicate values)
print(x)

y = np.random.choice(z,3) # (array, size) ----> gives the random values from the range equal to the size
print(z)
print(y)

(2, 6)
12


[5 9 5]
[ 1  5  8 32  5]
[32  1 32]


***Broadcasting***

In [ ]:
a = np.array([1,3,5,7,4])
b = np.array([1,5,9,0,2])
c = np.array([4,5,7])

l = [1,4,7,8,'yoo', False, 'int']

print(a)
print(b)

print(a*2)
print(a+b)
print(a-b)
print('\n',a*b)
print('\n',b/a)
# print(a*c)
# print(a/c)
# print(b*c)

print(l*2)



[1 3 5 7 4]
[1 5 9 0 2]
[ 2  6 10 14  8]
[ 2  8 14  7  6]
[ 0 -2 -4  7  2]

 [ 1 15 45  0  8]

 [1.         1.66666667 1.8        0.         0.5       ]
[1, 4, 7, 8, 'yoo', False, 'int', 1, 4, 7, 8, 'yoo', False, 'int']


reshape()
transpose()
concatenate()

In [ ]:
a = np.random.randint(2,20,12)
print(a)

c =  np.random.randint(2,20,12)

b = a.reshape(4,3)
print(b)



z = np.transpose(b)
print("\n", z)

print('\n',np.concatenate((b,b),axis=-1))

# print(np.concatenate())



[ 6 12 16  6  2  9  7 15 17  9  8 13]
[[ 6 12 16]
 [ 6  2  9]
 [ 7 15 17]
 [ 9  8 13]]

 [[ 6  6  7  9]
 [12  2 15  8]
 [16  9 17 13]]

 [[ 6 12 16  6 12 16]
 [ 6  2  9  6  2  9]
 [ 7 15 17  7 15 17]
 [ 9  8 13  9  8 13]]


In [176]:
a = np.random.randint(2,20,12)
print(a)
b = np.sort(a)
print('\n',b)
c = np.sum((a,b))
print('\n',c)
print(np.mean(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))
print(np.unique(a))


[15 13 11  6 10 10 11 13 10 16 10 14]

 [ 6 10 10 10 10 11 11 13 13 14 15 16]

 278
11.583333333333334
2.628635049264584
6
16
[ 6 10 11 13 14 15 16]


# Game-1

In [207]:
a = (input("Give your 7-days' score :  ").split(' '))
# print(a)
b = np.zeros(7)
for i in range (0,7):
  b[i] = int(a[i])
# print(b)
d = np.array(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'])
print("\n")
for i in range (0,7):
  print("Score on ",d[i]," : ", b[i])
print("\nMean of the score is :",np.mean(b))

print("\nTotal Runs :",np.sum(b))


Give your 7-days' score :  1 2 3 4 5 6 7


Score on  Mon  :  1.0
Score on  Tue  :  2.0
Score on  Wed  :  3.0
Score on  Thu  :  4.0
Score on  Fri  :  5.0
Score on  Sat  :  6.0
Score on  Sun  :  7.0

Mean of the score is :  4.0

Total Runs : 28.0


# homework awaiting